### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by lgrkvst** [BrobridgeOrg/atomic-jetstream#1]
Great work, and the implementation looks really nice!

Do you have any plans on supporting kv store on top of jetstream?

(https://docs.nats.io/using-nats/developer/develop_jetstream/kv)

**Comment by cfsghost** [comment]
I would say the answer is absolutely yes.

The KV support is in our roadmap. Actually, we have an internal version already to support KV for our enterprise customers.

This project aims to provide a way for general use to access JetStream on Node-RED platform. It's porting functions from the works we did on the client-side.

**Comment by lgrkvst** [comment]
Great! Looking forward to following the development!
