### ISSUE TITLE
The publisher node does not create the stream and there is no Documentaiton about it.

### ISSUE THREAD

**Issue by abaKurager** [BrobridgeOrg/atomic-jetstream#2]
Hello, thank you for your implementation of NATS JetStream.
I ve just tested your nodes and they work find.
I found that the stream has to be created from a console rather than the publisher node creating it.
I had to test every approach to solve the test, since there is no documentation about the node.

Anyhow, thank you very much for the implementation.

**Comment by cfsghost** [comment]
Still in the early stage. Documentation is low priority for now.

All question are welcome. :-)
